user_email_verification.settings:
  type: config_object
  label: 'User Email Verification settings'
  mapping:
    skip_roles:
      type: sequence
      label: 'Skip roles'
      sequence:
        type: string
        label: 'User roles to skip'
    validate_interval:
      type: integer
      label: 'Verification time interval'
    num_reminders:
      type: integer
      label: 'Quantity of reminders'
    mail_subject:
      type: label
      label: 'Verification mail subject'
    mail_body:
      type: text
      label: 'Verification mail body'
    extended_enable:
      type: boolean
      label: ''
    extended_validate_interval:
      type: integer
      label: 'Extended verification time interval'
    extended_mail_subject:
      type: label
      label: 'Extended verification mail subject'
    extended_mail_body:
      type: text
      label: 'Extended verification mail body'

block.settings.user_email_verification_notification:
  type: block_settings
  label: 'User Email verification notification'
  mapping:
    notification:
      type: mapping
      label: 'Notification message'
      mapping:
        value:
          type: text
          label: 'Notification message text'
        format:
          type: string
          label: 'Notification message format'
